<feat> : Выполнение 9 спринта.
Wirt150/java-filmorate pull request #1
Opened 2022-08-07 09:37 UTC by Wirt150

Выполнено согласно тз 9 спринта. Не сделал тесты так как валидация проходит на уровне создания объекта через аннотации.

2022-08-07 15:27 UTC, Frilock requested changes
Добрый день. Один комментарий к pom файлу, остальное все ок.

2022-08-07 15:27 UTC, Frilock commented on pom.xml
> +        <version>2.7.2</version>
Версии библиотек правильнее указывать в одном месте, а именно, в properties, чтобы при смене версии не приходилось лазить по иногда большому pom файлу.

2022-08-07 19:07 UTC, Wirt150 commented on pom.xml
> +        <version>2.7.2</version>
Добрый! В данном случае не получается присвоить ссылку из properties так как это блок parent и ide выдает вот такую ошибку : "Properties in parent definition are prohibited "

2022-08-10 10:22 UTC, Frilock requested changes
Добрый день, вижу у Вас получилось сделать абстракцию, здорово.
По заданию: на мой взгляд, все же стоит написать пару тестов на логику хотя бы, чтобы сделать покрытие. Опечатка в названии пакета. Кроме того, на мой взгляд, над интерфейсом ставить аннотацию не нужно, главное, чтобы они стояли над реализациями данного интерфейса.

2022-08-10 10:22 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/RestAbstractController.java
> +
Лишние пропуски

2022-08-10 10:22 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/validaror/ValidateDate.java
> +package ru.yandex.practicum.filmorate.validaror;
Опечатка в названии пакета?

2022-08-10 10:22 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Пару тестов на логику лучше бы добавить все таки =)

2022-08-10 10:22 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/ServiceWorkFilmDto.java
> +    public List<FilmDto> rerunAll() {
А почему такое название? оно как то не соответствует логике метода

2022-08-10 10:22 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/ServiceWorkDto.java
> +@Component
Аннотация не нужна как мне кажется. Главное чтоб над реализациями стояли

2022-08-10 22:59 UTC, Wirt150 commented on src/main/java/ru/yandex/practicum/filmorate/service/ServiceWorkDto.java
> +@Component
> Аннотация не нужна как мне кажется. Главное чтоб над реализациями стояли

Без нее spring и ide ругаются что неизвестная иньекция как на скриншоте который я скидывал в слаке.

2022-08-12 08:12 UTC, Frilock approved these changes
Здорово. Принято

2022-08-12 08:12 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/controller/RestControllerTest.java
> +        assertEquals(1, dtoList.size(), "������ ������� ������� ���� ����� 1.");
Кодировка какая то странная =)

2022-08-12 22:38 UTC, merged