Add database
Wirt150/java-filmorate pull request #4
Opened 2022-09-18 11:57 UTC by Wirt150

Выполнение 12 спринта. Переделал хранилища в Dao сервисы, разделил интерфейсы с доступом к базе данных что бы не дублировать код в Mpa и Genre контроллерах при этом сохранив жесткую привязку сервисного слоя к методам работы с БД. Поднял отдельно тестовую базу и переписал тесты под новую логику.

2022-09-18 15:42 UTC, Frilock requested changes
Добрый день, все очень понравилось, работа отличная. Пара комментариев, один с вопросом про возможное NPE в маппере, кроме того, просьба перенести мапперы в отдельный пакет. Причину указал в комментарии

2022-09-18 15:42 UTC, Frilock commented on pom.xml
> +            <version>2.7.3</version>
По моему тут не нужно версию указывать, подставится версия из parent, либо тогда версию лучше перенести в properties

2022-09-18 15:42 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/DtoServiceExtended.java
> +@Component
Над интерфейсами лучше не ставить аннотации для бинов, достаточно их поставить только над их реализациями

2022-09-18 15:42 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/util/Mappers.java
> +                    .birthday(rs.getDate("BIRTHDAY").toLocalDate())
Дата всегда будет заполнена? Если же нет, вы в данном месте получите NPE. Ответьте в комментарии пожалуйста, либо поправьте

2022-09-18 15:42 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/util/Mappers.java
> +    public static class FilmRowMapper implements RowMapper<FilmDto> {
На мой взгляд, Не очень хорошая практика пихать 5 классов в один. Лучше отдельный слой сделать для мапперов и для каждой сущности сделать отдельный класс. Объясню почему я так думаю: кол-во сущностей может расти и расти сильно, тогда Вам придется новые мапперы пихать сюда же. Будет не очень красиво

2022-09-18 15:42 UTC, Frilock commented on src/main/resources/banner.txt
> +Powered by Spring Boot ${spring-boot.version}
Подскажите для чего этот файл?)

2022-09-18 21:50 UTC, Wirt150 commented on pom.xml
> +            <version>2.7.3</version>
Поправил, там просто я так понял нашли уязвимость и мавен это подсвечивает. Версию я для проверки менял.

2022-09-18 22:09 UTC, Wirt150 commented on src/main/java/ru/yandex/practicum/filmorate/service/DtoServiceExtended.java
> +@Component
Если их не ставить при инъекции в абстрактных методах через дженерики спринг ругается. Я писал об этом в слаке. Приложение запускается но вроде спринг не глупый. Ошибка:

Could not autowire. No beans of 'DtoService<T>' type found.

2022-09-18 22:17 UTC, Wirt150 commented on src/main/java/ru/yandex/practicum/filmorate/util/Mappers.java
> +                    .birthday(rs.getDate("BIRTHDAY").toLocalDate())
Добавил проверку на пустоту и null на уровне валидации Dto,

2022-09-18 22:26 UTC, Wirt150 commented on src/main/resources/banner.txt
> +Powered by Spring Boot ${spring-boot.version}
Этот файл говорит консольке что выводить на экран во врменя запуска спринга. В моем случае он пишет filmorate , а не Spring. Картинку не могу приложить, но туда можно добавить любое описание текстовое, короче как README файл но для спринга.

2022-09-18 22:37 UTC, Wirt150 commented on src/main/java/ru/yandex/practicum/filmorate/util/Mappers.java
> +    public static class FilmRowMapper implements RowMapper<FilmDto> {
Понял, поправил.

2022-09-19 16:56 UTC, Frilock commented on src/main/resources/banner.txt
> +Powered by Spring Boot ${spring-boot.version}
Понял, не сталкивался с таким.

2022-09-19 17:12 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/DtoServiceExtended.java
> +@Component
Я Вас уверяю, на интерфейсе не обязательна аннотация для бина, если над реализациями они стоят. Я запустил Ваш код, удалил аннотации с интерфейсов. Варнингов нет, ошибок нет. 
Можем попробовать разобраться, пришлите скрины пожалуйста или по больше подробностей. В каком классе у вас ошибка?

2022-09-19 17:13 UTC, Frilock approved these changes
Работу принял. Но в качестве факультатива давайте разберемся с аннотациями над интерфейсами, пришлите мне где у Вас возникает ошибка. Я запустил Ваш код, удалив аннотации над интерфейсами. Ошибок нет, варнингов тоже не вижу

2022-09-28 21:24 UTC, merged